config/routes.rb
Rails.application.routes.draw do
  get 'users/:username', to: "users#show", as: 'user'
  resources :items
  resources :tweets
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
    get "signin", to: 'devise/sessions#new'
    delete "signout", to: 'devise/sessions#destroy'
    get "signup", to: 'devise/registration#new'
  end

  # http://127.0.0.1:3000/
  root 'pages#home'

  get 'about' => 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_authorization.rb
class AdminAuthorization < ActiveAdmin::AuthorizationAdapter 
  
  def authorized?(action, subject = nil)
    # si el user está logueado y es admin?
    user && user.admin?
  end
end

#! UNIQUE WAY TO CREATE A ADMIN FOR THE FIRST TIME => rails console
# user = User.find_by(email: "example@mail.com")
# user.email => example@mail.com
# user.id => 1
# user.created_at => Wed, 14 Jun 2023 21:15:12.274983000 UTC +00:00
# user.admin => false 
# user.admin = true
# user => #<User id: 1, email: "example@mail.com", created_at: "2023-06-14 21:15:12.274983000 +0000", updated_at: "2023-06-14 21:15:12.274983000 +0000", admin: true>
# user.save =>   TRANSACTION (0.1ms)  begin transaction
  # User Update (13.6ms)  UPDATE "users" SET "updated_at" = ?, "admin" = ? WHERE "users"."id" = ?  [["updated_at", "2023-06-16 21:09:28.842872"], ["admin", 1], ["id", 1]]
  # TRANSACTION (3.0ms)  commit transaction

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,  :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  # rails validations
  # si el del current_user y existe tweet
  validates :user, presence: true
  # si existe content
  validates :content, presence: true, length: { maximum: 280 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
  has_many :items

  validates :username, presence: true, uniqueness: true, length: { minimum: 6 }
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def access_denied(exception)
    # redirigir al root with an alert if the user try access to a place they cant
    redirect_to root_path, alert: exception.message
  end

  protected 

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  # GET /items
  def index
    @items = Item.all
  end

  # GET /items/1
  def show
    @item = Item.find(params[:id])
  end

  # GET /items/new
  def new
    @item = current_user.items.new
  end

  # GET /items/1/edit
  def edit
    @item = current_user.items.find(params[:id])
  end

  # POST /items
  def create
    @item = current_user.items.new(item_params)

      if @item.save
        redirect_to @item, notice: "Item was successfully created."
      else
        render :new
      end
  end

  # PATCH/PUT /items/1
  def update
    @item = current_user.items.find(params[:id])
      if @item.update(item_params)
        redirect_to @item, notice: "Item was successfully updated."
      else
        render :edit
      end
  end

  # DELETE /items/1
  def destroy
    @item = current_user.items.find(params[:id])

    @item.destroy
    redirect_to items_url, notice: "Item was successfully destroyed."
  end

  private

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:title, :url, :text)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  # GET /tweets or /tweets.json
  def index
    #Tweet with capitalize, refers to a model
    @tweets = Tweet.all
  end

  # GET /tweets/1 or /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])

  end

  # GET /tweets/new
  def new 
    #userId set to the tweetId
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1/edit
  def edit
    @tweet = current_user.tweets.find(params[:id])

  end

  # POST /tweets or /tweets.json
  def create
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to tweet_url(@tweet), notice: "Tweet was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    @tweet = current_user.tweets.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy
      redirect_to tweets_url, notice: "Tweet was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(username: params[:username])
    @tweets = @user.tweets
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_message do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_area :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: "form-control" %>
  </div>

  <p><strong>or</strong></p>
  
  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_field :text, class: "form-control" %>
  </div>

  <%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <p>
    <strong>User:</strong>
    <%= item.user_id %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= item.title %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= item.url %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= item.text %>
  </p>

</div>

app/views/items/edit.html.erb
<div class="container">
  <h1>Editing item</h1>
  <%= render "form", item: @item %>

  
  <div>
    <%= link_to "Show", @item %> |
    <%= link_to "Back", items_path %>
  </div>
</div>

app/views/items/index.html.erb
<div class="container">
  <h1>Items</h1>
  <table>
    <thead>
      <tr>
        <th>User</th>
        <th>Title</th>
        <th>Url</th>
        <th>Text</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
      <tr>
        <td><%= item.user.username %></td>
        <td><%= item.title %></td>
        <td><%= item.url %></td>
        <td><%= item.text %></td>
        <td><%= link_to "Show", item %></td>
        <% if item.user == current_user %>
          <td> <%= link_to "Edit", edit_item_path(item) %> </td>
          <td> <%= link_to "Delete", item, method: :delete, data: { confirm: "Are you sure?" } %> </td>
        <% end %>
      </tr>
    </tbody>
  </table>
  
  <br>
  <%= link_to "New item", new_item_path %>
</div>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/show.html.erb
<div class="container">
  <p><strong>User:</strong>
    <%= @item.user.username %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= @item.title %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= @item.url %>
  </p>
  
  <% if @item.text? %>
    <p>
      <strong>Text:</strong>
      <%= @item.text %>
    </p>
  <% end %>
  

  <% if @item.user == current_user %> |
    <%= link_to "Edit this item", edit_item_path(@item) %> |
  <% end %>
  <%= link_to "Back to items", items_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quotes rock band project</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  <%# Navigation bar %>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <%= link_to "One Month Rails", root_path, class: "navbar-brand" %>
          <ul class="nav navbar-nav">
            <li class='nav-item'>
              <%= link_to "Home", root_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
            <% if user_signed_in? %>
              <li class="nav-item pull-md-right"><%= link_to "Log out", signout_path, method: :delete, class: "nav-link" %> </li>
            <% else %> 
              <li class="nav-item pull-md-right"> 
                <%= link_to "Sign up", signup_path, class: "btn btn-primary" %> 
              </li>
              <li class="nav-item pull-md-right"> 
                <%= link_to "Sign in", signin_path, class: "nav-link" %> 
              </li>
            <% end %>
          </ul>
      </div>
    </nav>

    <%# Flash messages %>
        <% flash.each do |name, message| %>
        <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
        <% end %>

    <%# Page content %>
    <%= yield %>

    <%# Footer %>
    <footer class='small text-muted'>
      <div class='container'>
        <hr>
        <center>
          <p>2023 One Month</p>
        </center>
      </div>
    </footer>
  
  </body>
</html>

app/views/pages/about.html.erb
<div class='jumbotron'>
  <div class='container'>
    <h1>About us</h1>
    <h3>Musicians Tribute Web Page</h3> </br> 
    <p>This is the sample project I built for <a href="https://onemonthrails.com">One Month Rails.</a> </br>
    The web page allows users to register, log in, and log out. Users can create new "tweets" dedicated to their favorite musicians and edit their own tweets.</p>
  </div>
</div>

app/views/pages/home.html.erb
<% if user_signed_in? %>
  <div class='jumbotron jumbotron-home'>
    <div class='container'>
      <h1>Welcome back! </h1>
    </div>
  </div>
<% else %>
  <div class='jumbotron jumbotron-home'>
    <div class='container'>
      <h1 class="text-light">Quotes from rock bands!</h1>
      <p class="text-light"> <strong>
      “When you go through tragedy, you can either let that destroy you and you become bitter and never let it go, or you can let it make you stronger and let it make you grow. And that's what I did. My lyrics are coming from a place that I want people to relate to and feel that they're not alone.”
      </strong>
      
      </p>
    
    </div>
  </div>

  <div class='container'>
    <div class='row'>
      <div class='col-md-4'>
        <h4>Chester Bennington</h4>
        <p>“When I'm writing, I'm constantly thinking about myself, because it's the only experience I have to draw on. And I don't see an exact reflection of myself in every face in the audience, but I know that my songs have validity to them, and that's why the fans are there.” </p>
      </div>

      <div class='col-md-4'>
        <h4>Amy Lee</h4>
        <p>“I know how it feels to be completely alone and helpless, and the last thing you want to hear in that situation is, 'It's going to be OK.' "The only thing that seems to really help is that someone else who has felt that low expressing those feelings to you.”
   </p>
      </div>

      <div class='col-md-4'>
        <h4>Avenged Sevenfold</h4>
        <p>“How do I live without the ones I love? Time still turns the pages of the book its burned. Place and time always on my mind. I have so much to say but your so far away.”</p>
      </div>
    </div>
  </div>
<% end %>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control" %>
  </div>


  <%= form.submit class: "btn btn-primary" %>

<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">
  <p>
    <strong>User:</strong>
    <%= tweet.user_id %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= tweet.content %>
  </p>

</div>

app/views/tweets/edit.html.erb
<div class="container">

  <h1>Editing tweet</h1>

  <%= render "form", tweet: @tweet %>

  <%= link_to "Show this tweet", @tweet %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/index.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-4">
      <div class="card card-block">
        <h4 class="card-title">Your account</h4>
        <p class="card-text"><% link_to current_user.username, user_path(current_user.username) %></p>
      </div>
    </div>

    <div class="col-md-8">
      <% if user_signed_in? %>
        <% link_to "New tweet", new_tweet_path %>
      <% end %> 

    <ul class="list-group">
        <% @tweets.each do |tweet| %>
          <% link_to tweet, class: "list-group-item list-group-item-action" do %>
          <h5 class="list-group-item-heading"> <%= tweet.user.username %> </h5>
          <p class="list-group-item-text"> <%= tweet.content %> </p>
          <% end %>
        <% end %>  
      </ul>
    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<div class="container">
  <h1>New tweet</h1>
  
  <%= render "form", tweet: @tweet %>

<br>

  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<div class="container">
  <div class="row">
    <div class="offset-md-2 col-md-8">
      <div class="card card-block">
        <h4 class="card-title"><%=link_to @tweet.user.username, user_path(@tweet.user.username) %></h4>
        <p class="card-text"><%= @tweet.content %></p>
        <% if @tweet.user == current_user %>
          <%= link_to "Edit", edit_tweet_path(@tweet), class: "card-link" %>
          <%= link_to "Delete", @tweet, method: :delete, class: "card-link" %>
        <% end %>
        <%= link_to "Back to tweets", tweets_path, class: "card-link" %>
      </div>
    </div>
  </div>
</div>  

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="card card-block">
        <h4 class="card-title"><%= @user.username %></h4>
        <p class="card-text"><%= @user.name %></p> 
      </div>
    </div>
    <div class="col-md-4">
      <ul class="list-group">
        <% @tweets.each do |tweet| %>
        <%= link_to tweet, class: "list-group-item list-group-item-action" do %>
          <h5 class="list-group-item-heading"><%= tweet.user.username%></h5>
          <p class="list-group-item-text"><%= tweet.content %></p>
          <% end %>
      </ul>
    </div>
  </div>
</div>